import type { GuidedStep } from './types';

export interface WorkflowDefinition {
  workflowType: string;
  title: string;
  description: string;
  steps: GuidedStep[];
}

export const WORKFLOW_DEFINITIONS: Record<string, WorkflowDefinition> = {
  RECEIVE_STOCK: {
    workflowType: 'RECEIVE_STOCK',
    title: 'Receive Stock Batch',
    description: 'Guides you step-by-step through registering an incoming stock batch, entering batch number, storage location, unit cost, and expiry date.',
    steps: [
      {
        stepNumber: 1,
        action: 'NAVIGATE',
        route: '/inventory',
        tab: 'inventory',
        target: 'nav-inventory',
        instruction: 'Click on the Stock & Batches tab in the navigation bar to open the inventory workspace.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Navigation Bar: Stock & Batches',
      },
      {
        stepNumber: 2,
        action: 'CLICK',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-stock-button',
        instruction: 'Click the Receive Stock button to launch the incoming shipment intake dialog.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Receive Stock Button',
      },
      {
        stepNumber: 3,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-ingredient-select',
        instruction: 'Select the ingredient you are receiving from the catalog dropdown.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Ingredient Dropdown',
      },
      {
        stepNumber: 4,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-location-select',
        instruction: 'Choose the storage location where this batch will be placed (e.g. Walk-in Cooler or Dry Storage).',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Storage Location Dropdown',
      },
      {
        stepNumber: 5,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-batch-input',
        instruction: 'Enter the supplier batch/lot number found on the shipment packaging.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Batch Number Field',
      },
      {
        stepNumber: 6,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-quantity-input',
        instruction: 'Enter the exact quantity received (in units like kg, liters, or packs).',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Quantity Field',
      },
      {
        stepNumber: 7,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-unit-cost-input',
        instruction: 'Verify or input the purchase cost per unit from your supplier delivery invoice.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Unit Cost Field',
      },
      {
        stepNumber: 8,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-expiry-input',
        instruction: 'Select the expiration date printed on the batch for automated FEFO stock rotation.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Expiration Date Picker',
      },
      {
        stepNumber: 9,
        action: 'CONFIRM',
        route: '/inventory',
        tab: 'inventory',
        target: 'receive-submit-button',
        instruction: 'Review the details and click Receive Stock to commit the batch into live inventory.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Confirm Intake Button',
      },
    ],
  },
  CONSUME_STOCK: {
    workflowType: 'CONSUME_STOCK',
    title: 'Record Stock Consumption (FEFO)',
    description: 'Guides you through deducting stock for kitchen preparation using automated First-Expired, First-Out rules.',
    steps: [
      {
        stepNumber: 1,
        action: 'NAVIGATE',
        route: '/inventory',
        tab: 'inventory',
        target: 'nav-inventory',
        instruction: 'Click on the Stock & Batches tab in the navigation bar.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Navigation Bar: Stock & Batches',
      },
      {
        stepNumber: 2,
        action: 'CLICK',
        route: '/inventory',
        tab: 'inventory',
        target: 'consume-stock-button',
        instruction: 'Click the Consume Stock (FEFO) button.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Consume Stock Button',
      },
      {
        stepNumber: 3,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'consume-ingredient-select',
        instruction: 'Select the ingredient consumed by kitchen staff.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Ingredient Dropdown',
      },
      {
        stepNumber: 4,
        action: 'INPUT',
        route: '/inventory',
        tab: 'inventory',
        target: 'consume-quantity-input',
        instruction: 'Enter the amount used.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Quantity Input',
      },
      {
        stepNumber: 5,
        action: 'CONFIRM',
        route: '/inventory',
        tab: 'inventory',
        target: 'consume-submit-button',
        instruction: 'Click Confirm to deplete stock via FEFO.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Confirm Button',
      },
    ],
  },
  VIEW_LOW_STOCK: {
    workflowType: 'VIEW_LOW_STOCK',
    title: 'Review Low Stock & Safety Alerts',
    description: 'Guides you through locating and analyzing critical stock items below minimum thresholds.',
    steps: [
      {
        stepNumber: 1,
        action: 'NAVIGATE',
        route: '/inventory',
        tab: 'inventory',
        target: 'nav-inventory',
        instruction: 'Navigate to the Stock & Batches view.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Stock & Batches Tab',
      },
      {
        stepNumber: 2,
        action: 'INSPECT',
        route: '/inventory',
        tab: 'inventory',
        target: 'low-stock-alert-card',
        instruction: 'Inspect the Stock Alerts summary card to view depleted and low stock levels.',
        status: 'PENDING',
        waitForUserAction: true,
        targetDescription: 'Stock Alerts KPI Card',
      },
    ],
  },
};
